import Foundation

enum StoneData {
    static let stones: [StoneSpec] = [
        StoneSpec(id: "river_flat", name: "River Flat",
                  blurb: "A palm-smooth skipping stone from the shallows. Honest and even-tempered.",
                  weight: 1.0, lift: 1.0, window: 1.0,
                  bodyHex: 0x8B8378, sheenHex: 0xC9C2B4, speckHex: 0x6E675D,
                  unlock: .start),
        StoneSpec(id: "slate_chip", name: "Slate Chip",
                  blurb: "Thin and forgiving. It hangs in the air a breath longer, waiting for your tap.",
                  weight: 0.95, lift: 1.0, window: 1.12,
                  bodyHex: 0x5D6B75, sheenHex: 0xABBCC6, speckHex: 0x42505A,
                  unlock: .stars(6)),
        StoneSpec(id: "granite_egg", name: "Granite Egg",
                  blurb: "Heavy and eager. Launches hard, but the timing beat comes up fast.",
                  weight: 1.1, lift: 0.97, window: 0.92,
                  bodyHex: 0x9A8F8A, sheenHex: 0xD8CFC8, speckHex: 0x77675F,
                  unlock: .stars(12)),
        StoneSpec(id: "clay_rounder", name: "Clay Rounder",
                  blurb: "Sun-baked and light. Rises off the water with a gentle spring.",
                  weight: 0.98, lift: 1.06, window: 1.0,
                  bodyHex: 0xB57A55, sheenHex: 0xE8B58C, speckHex: 0x8C5A3C,
                  unlock: .stars(20)),
        StoneSpec(id: "sea_glass", name: "Sea Glass",
                  blurb: "Frosted green and calm. The widest timing windows on the shore, if you can live with less bounce.",
                  weight: 0.95, lift: 0.94, window: 1.22,
                  bodyHex: 0x7FB89E, sheenHex: 0xC8EBD8, speckHex: 0x578A72,
                  unlock: .stars(28)),
        StoneSpec(id: "basalt_wedge", name: "Basalt Wedge",
                  blurb: "Volcanic and blunt. Cuts through wind with a flat, fast flight.",
                  weight: 1.08, lift: 0.95, window: 1.0,
                  bodyHex: 0x4A4A52, sheenHex: 0x8E8E9C, speckHex: 0x32323A,
                  unlock: .stars(38)),
        StoneSpec(id: "amber_drop", name: "Amber Drop",
                  blurb: "Warm honey-glass with an easy temper. Lifts kindly and taps kindly.",
                  weight: 1.0, lift: 1.07, window: 1.06,
                  bodyHex: 0xD29A3F, sheenHex: 0xF6D488, speckHex: 0xA8742A,
                  unlock: .stars(50)),
        StoneSpec(id: "obsidian_disc", name: "Obsidian Disc",
                  blurb: "A black mirror. Fast and springy, but it asks for sharp hands.",
                  weight: 1.07, lift: 1.08, window: 0.9,
                  bodyHex: 0x2B2B33, sheenHex: 0x6E6E85, speckHex: 0x191920,
                  unlock: .stars(64)),
        StoneSpec(id: "pearl_button", name: "Pearl Button",
                  blurb: "Mother-of-pearl, cool to the touch. Time slows a little when it falls.",
                  weight: 0.94, lift: 1.0, window: 1.3,
                  bodyHex: 0xE3DDD3, sheenHex: 0xFFFBF0, speckHex: 0xBAB2A4,
                  unlock: .stars(80)),
        StoneSpec(id: "meteor_chip", name: "Meteor Chip",
                  blurb: "A shard of somewhere else. The hardest throw on the shore.",
                  weight: 1.16, lift: 1.02, window: 0.94,
                  bodyHex: 0x6B4F63, sheenHex: 0xB08CAB, speckHex: 0x4A3545,
                  unlock: .stars(100)),
        StoneSpec(id: "moonstone", name: "Moonstone",
                  blurb: "Found only by those who come back morning after morning.",
                  weight: 0.97, lift: 1.05, window: 1.15,
                  bodyHex: 0xA8B4D8, sheenHex: 0xE6ECFF, speckHex: 0x8390B8,
                  unlock: .streak(3)),
        StoneSpec(id: "sunstone_heart", name: "Sunstone Heart",
                  blurb: "The whole sunset in one stone. Everything, a little better.",
                  weight: 1.06, lift: 1.06, window: 1.08,
                  bodyHex: 0xD96D3F, sheenHex: 0xFFC08A, speckHex: 0xA84E2C,
                  unlock: .stars(130))
    ]

    static func stone(id: String) -> StoneSpec {
        stones.first { $0.id == id } ?? stones[0]
    }
}

enum AchievementData {
    static let all: [AchievementSpec] = [
        AchievementSpec(id: "first_skip", name: "First Skip",
                        detail: "Skip a stone off the water once.",
                        metric: .totalSkips(1)),
        AchievementSpec(id: "hop_3", name: "Triple Hop",
                        detail: "Skip 3 times in a single throw.",
                        metric: .skipsInOneThrow(3)),
        AchievementSpec(id: "hop_6", name: "Six Stone",
                        detail: "Skip 6 times in a single throw.",
                        metric: .skipsInOneThrow(6)),
        AchievementSpec(id: "hop_10", name: "Ten Touch",
                        detail: "Skip 10 times in a single throw.",
                        metric: .skipsInOneThrow(10)),
        AchievementSpec(id: "perfect_1", name: "First Perfect",
                        detail: "Land one perfectly timed skip.",
                        metric: .perfectsTotal(1)),
        AchievementSpec(id: "perfect_25", name: "Steady Hands",
                        detail: "Land 25 perfect skips in total.",
                        metric: .perfectsTotal(25)),
        AchievementSpec(id: "perfect_100", name: "Water Whisperer",
                        detail: "Land 100 perfect skips in total.",
                        metric: .perfectsTotal(100)),
        AchievementSpec(id: "ring_1", name: "Ring Rookie",
                        detail: "Pass through your first floating ring.",
                        metric: .ringsTotal(1)),
        AchievementSpec(id: "ring_30", name: "Ring Collector",
                        detail: "Pass through 30 rings in total.",
                        metric: .ringsTotal(30)),
        AchievementSpec(id: "pad_10", name: "Pad Hopper",
                        detail: "Bounce off 10 lily pads in total.",
                        metric: .padsTotal(10)),
        AchievementSpec(id: "sunk_25", name: "Deep Sleeper",
                        detail: "Sink 25 stones. The lake keeps them safe.",
                        metric: .sunkTotal(25)),
        AchievementSpec(id: "dist_60", name: "Half Field",
                        detail: "Throw a stone 60 meters.",
                        metric: .longestThrow(60)),
        AchievementSpec(id: "dist_100", name: "Century Line",
                        detail: "Throw a stone 100 meters.",
                        metric: .longestThrow(100)),
        AchievementSpec(id: "dist_140", name: "Horizon Caller",
                        detail: "Throw a stone 140 meters.",
                        metric: .longestThrow(140)),
        AchievementSpec(id: "shore_0", name: "Dawn Kept",
                        detail: "Earn a star on every Dawn Pond level.",
                        metric: .shoreCleared(0)),
        AchievementSpec(id: "shore_1", name: "Creek Kept",
                        detail: "Earn a star on every Willow Creek level.",
                        metric: .shoreCleared(1)),
        AchievementSpec(id: "shore_2", name: "Fjord Kept",
                        detail: "Earn a star on every Windy Fjord level.",
                        metric: .shoreCleared(2)),
        AchievementSpec(id: "shore_3", name: "Lagoon Kept",
                        detail: "Earn a star on every Glass Lagoon level.",
                        metric: .shoreCleared(3)),
        AchievementSpec(id: "shore_4", name: "Sea Kept",
                        detail: "Earn a star on every Sunset Sea level.",
                        metric: .shoreCleared(4)),
        AchievementSpec(id: "stars_90", name: "Star Gatherer",
                        detail: "Collect 90 stars across all shores.",
                        metric: .starsTotal(90)),
        AchievementSpec(id: "zen_80", name: "Zen Drifter",
                        detail: "Reach 80 meters on the Zen Shore.",
                        metric: .zenBest(80)),
        AchievementSpec(id: "streak_7", name: "Week of Mornings",
                        detail: "Keep a 7-day Daily Throw streak.",
                        metric: .dailyStreak(7))
    ]
}
